import { DiagnosticColor, TestMode, TestSequenceConfig, DeviceCategory } from "./types";

export const DIAGNOSTIC_COLORS: Record<string, DiagnosticColor> = {
  black: {
    id: "black",
    name: "Pure Black",
    hex: "#000000",
    type: "solid",
    description: "Look for permanently lit (stuck) pixels that glow red, green, blue, or white against the dark backdrop.",
    instructions: "Look for glowing dots or IPS glow along the edges.",
    hudDarkText: false,
  },
  white: {
    id: "white",
    name: "Pure White",
    hex: "#FFFFFF",
    type: "solid",
    description: "Look for dead pixels (dark or completely black dots) and dust or foreign debris behind the panel.",
    instructions: "Look for dark speckles or uneven brightness patches.",
    hudDarkText: true,
  },
  red: {
    id: "red",
    name: "Pure Red",
    hex: "#FF0000",
    type: "solid",
    description: "Inspect red subpixel health. A failed red subpixel will appear black, dark, or distorted.",
    instructions: "Check if the red field is fully saturated and uniform without black dots.",
    hudDarkText: false,
  },
  green: {
    id: "green",
    name: "Pure Green",
    hex: "#00FF00",
    type: "solid",
    description: "Inspect green subpixel health. Green is the most visible channel to the human eye.",
    instructions: "Inspect green luminance uniformity across the entire panel.",
    hudDarkText: true,
  },
  blue: {
    id: "blue",
    name: "Pure Blue",
    hex: "#0000FF",
    type: "solid",
    description: "Inspect blue subpixel health. Blue subpixels are commonly prone to premature wear in older OLED panels.",
    instructions: "Check for missing blue dots or dim areas.",
    hudDarkText: false,
  },
  yellow: {
    id: "yellow",
    name: "Pure Yellow",
    hex: "#FFFF00",
    type: "solid",
    description: "Combination of Red + Green subpixels. Helps identify if either subpixel channel is weak or missing.",
    instructions: "Check for color consistency across all screen sectors.",
    hudDarkText: true,
  },
  cyan: {
    id: "cyan",
    name: "Pure Cyan",
    hex: "#00FFFF",
    type: "solid",
    description: "Combination of Green + Blue subpixels. Tests secondary color mixing accuracy.",
    instructions: "Inspect for subpixel tinting or dead sub-elements.",
    hudDarkText: true,
  },
  magenta: {
    id: "magenta",
    name: "Pure Magenta",
    hex: "#FF00FF",
    type: "solid",
    description: "Combination of Red + Blue subpixels. Useful for diagnosing stuck or disabled green subpixels.",
    instructions: "Inspect for color separation or missing subpixels.",
    hudDarkText: false,
  },
  gray: {
    id: "gray",
    name: "Neutral Gray (50%)",
    hex: "#808080",
    type: "solid",
    description: "50% mid-tone gray. Excellent for detecting Dirty Screen Effect (DSE), clouding, and panel tinting.",
    instructions: "Look for clouding, shadows, or color temperature shifts.",
    hudDarkText: false,
  },
  lightGray: {
    id: "light-gray",
    name: "Light Gray (82%)",
    hex: "#D3D3D3",
    type: "solid",
    description: "Light neutral gray. Helps identify subtle edge vignetting and backlight diffusion irregularities.",
    instructions: "Check corners and edges for vignetting or dim spots.",
    hudDarkText: true,
  },
  darkGray: {
    id: "dark-gray",
    name: "Dark Gray (20%)",
    hex: "#333333",
    type: "solid",
    description: "Near-black gray. Perfect for testing backlight bleed, IPS glow, and OLED near-black uniformity.",
    instructions: "Inspect in a dim room for light bleeding from the bezel corners.",
    hudDarkText: false,
  },
  gradientBW: {
    id: "gradient-bw",
    name: "Monochrome Gradient",
    hex: "#000000",
    type: "gradient",
    gradientCss: "linear-gradient(to right, #000000 0%, #FFFFFF 100%)",
    description: "Inspect tonal gradation from deep black to peak white. Look for severe stepping or color banding.",
    instructions: "Check if transitions appear smooth without harsh vertical step lines.",
    hudDarkText: false,
  },
  gradientRG: {
    id: "gradient-rg",
    name: "Red to Green Gradient",
    hex: "#FF0000",
    type: "gradient",
    gradientCss: "linear-gradient(to right, #FF0000 0%, #FFFF00 50%, #00FF00 100%)",
    description: "Tests color transition smoothly across red, yellow, and green spectrums.",
    instructions: "Observe the yellow midpoint transition for smooth blending.",
    hudDarkText: false,
  },
  gradientBG: {
    id: "gradient-bg",
    name: "Blue to Green Gradient",
    hex: "#0000FF",
    type: "gradient",
    gradientCss: "linear-gradient(to right, #0000FF 0%, #00FFFF 50%, #00FF00 100%)",
    description: "Tests blue-cyan-green color gradient rendering and panel gamma response.",
    instructions: "Check for smooth cyan blend in the center of the display.",
    hudDarkText: false,
  },
  gradientRB: {
    id: "gradient-rb",
    name: "Red to Blue Gradient",
    hex: "#FF0000",
    type: "gradient",
    gradientCss: "linear-gradient(to right, #FF0000 0%, #FF00FF 50%, #0000FF 100%)",
    description: "Tests magenta color fidelity and wide color gamut transitions.",
    instructions: "Ensure smooth magenta midpoint without harsh color breaks.",
    hudDarkText: false,
  },
};

export const TEST_SEQUENCES: Record<TestMode, TestSequenceConfig> = {
  "dead-pixel": {
    mode: "dead-pixel",
    title: "Dead Pixel Test",
    subtitle: "Identify inactive or permanently dark pixels",
    description: "A dead pixel remains off and appears as a black dot against bright backgrounds. This test cycles through high-contrast solid colors to reveal any non-responsive pixels.",
    colors: [
      DIAGNOSTIC_COLORS.white,
      DIAGNOSTIC_COLORS.lightGray,
      DIAGNOSTIC_COLORS.gray,
      DIAGNOSTIC_COLORS.red,
      DIAGNOSTIC_COLORS.green,
      DIAGNOSTIC_COLORS.blue,
      DIAGNOSTIC_COLORS.yellow,
      DIAGNOSTIC_COLORS.cyan,
      DIAGNOSTIC_COLORS.magenta,
      DIAGNOSTIC_COLORS.black,
    ],
    recommendedInterval: 2000,
  },
  "stuck-pixel": {
    mode: "stuck-pixel",
    title: "Stuck Pixel Test",
    subtitle: "Find pixels stuck on a specific color",
    description: "A stuck pixel remains constantly turned on in red, green, blue, or white. This sequence displays contrasting dark and complementary shades to pinpoint frozen subpixels.",
    colors: [
      DIAGNOSTIC_COLORS.black,
      DIAGNOSTIC_COLORS.darkGray,
      DIAGNOSTIC_COLORS.red,
      DIAGNOSTIC_COLORS.green,
      DIAGNOSTIC_COLORS.blue,
      DIAGNOSTIC_COLORS.magenta,
      DIAGNOSTIC_COLORS.cyan,
      DIAGNOSTIC_COLORS.yellow,
      DIAGNOSTIC_COLORS.white,
    ],
    recommendedInterval: 2000,
  },
  "color": {
    mode: "color",
    title: "Screen Color Test",
    subtitle: "Pure primary and secondary color diagnostics",
    description: "Verify color accuracy, subpixel health, and color rendition with standard RGB and CMY solid full-screen canvases.",
    colors: [
      DIAGNOSTIC_COLORS.red,
      DIAGNOSTIC_COLORS.green,
      DIAGNOSTIC_COLORS.blue,
      DIAGNOSTIC_COLORS.yellow,
      DIAGNOSTIC_COLORS.cyan,
      DIAGNOSTIC_COLORS.magenta,
      DIAGNOSTIC_COLORS.white,
      DIAGNOSTIC_COLORS.black,
    ],
    recommendedInterval: 2000,
  },
  "uniformity": {
    mode: "uniformity",
    title: "Screen Uniformity Test",
    subtitle: "Inspect brightness distribution & backlight bleed",
    description: "Evaluates panel uniformity, backlight bleeding, IPS glow, dirty screen effect (DSE), and corner vignetting across varying grayscale and pure color fields.",
    colors: [
      DIAGNOSTIC_COLORS.white,
      DIAGNOSTIC_COLORS.lightGray,
      DIAGNOSTIC_COLORS.gray,
      DIAGNOSTIC_COLORS.darkGray,
      DIAGNOSTIC_COLORS.black,
      DIAGNOSTIC_COLORS.red,
      DIAGNOSTIC_COLORS.green,
      DIAGNOSTIC_COLORS.blue,
    ],
    recommendedInterval: 3000,
  },
  "gradient": {
    mode: "gradient",
    title: "Gradient & Banding Test",
    subtitle: "Inspect smooth transitions & color stepping",
    description: "Evaluates the bit-depth smoothness of your display. Inspect whether color gradients blend seamlessly or show harsh vertical bands and posterization.",
    colors: [
      DIAGNOSTIC_COLORS.gradientBW,
      DIAGNOSTIC_COLORS.gradientRG,
      DIAGNOSTIC_COLORS.gradientBG,
      DIAGNOSTIC_COLORS.gradientRB,
    ],
    recommendedInterval: 3000,
  },
  "fullscreen": {
    mode: "fullscreen",
    title: "Complete Display Test",
    subtitle: "Comprehensive 15-step screen diagnostic sequence",
    description: "Runs the complete diagnostic suite including all 11 pure solid colors and 4 high-precision color gradients for exhaustive display inspection.",
    colors: [
      DIAGNOSTIC_COLORS.black,
      DIAGNOSTIC_COLORS.white,
      DIAGNOSTIC_COLORS.red,
      DIAGNOSTIC_COLORS.green,
      DIAGNOSTIC_COLORS.blue,
      DIAGNOSTIC_COLORS.yellow,
      DIAGNOSTIC_COLORS.cyan,
      DIAGNOSTIC_COLORS.magenta,
      DIAGNOSTIC_COLORS.gray,
      DIAGNOSTIC_COLORS.lightGray,
      DIAGNOSTIC_COLORS.darkGray,
      DIAGNOSTIC_COLORS.gradientBW,
      DIAGNOSTIC_COLORS.gradientRG,
      DIAGNOSTIC_COLORS.gradientBG,
      DIAGNOSTIC_COLORS.gradientRB,
    ],
    recommendedInterval: 2000,
  },
};

export const DEVICE_METADATA: Record<DeviceCategory, {
  name: string;
  tagline: string;
  description: string;
  displayTech: string;
  prepTips: string[];
  testSlug: string;
  deadSlug: string;
}> = {
  iphone: {
    name: "iPhone & iPad",
    tagline: "Test Super Retina OLED & Liquid Retina Displays",
    description: "Modern iPhones feature high-density Super Retina XDR OLED or Liquid Retina LCD panels. This diagnostic tests for dead subpixels, burn-in remnants, and OLED tinting.",
    displayTech: "Super Retina XDR OLED / Liquid Retina LCD (ProMotion 120Hz supported)",
    prepTips: [
      "Disable True Tone and Night Shift in Settings > Display & Brightness.",
      "Increase screen brightness to 80-100% for optimal subpixel visibility.",
      "Clean screen surface with a dry microfiber cloth to remove smudges.",
      "Swipe up or enter full-screen to hide Safari navigation bars.",
    ],
    testSlug: "/iphone-screen-test",
    deadSlug: "/iphone-dead-pixel-test",
  },
  android: {
    name: "Android Devices",
    tagline: "Test AMOLED, Dynamic AMOLED & LCD Displays",
    description: "Test Samsung Galaxy, Google Pixel, Xiaomi, OnePlus, and other Android smartphones and tablets for dead pixels, green-line defects, and AMOLED burn-in.",
    displayTech: "Dynamic AMOLED 2X, Super AMOLED, POLED, IPS LCD",
    prepTips: [
      "Turn off Eye Comfort Shield / Night Light in Quick Settings.",
      "Set display mode to 'Natural' or 'Standard' if evaluating true color fidelity.",
      "Maximize screen brightness and wipe away dust particles.",
      "Tap the Fullscreen button to hide the Android gesture bar / status bar.",
    ],
    testSlug: "/android-screen-test",
    deadSlug: "/android-dead-pixel-test",
  },
  mac: {
    name: "Mac & Apple Displays",
    tagline: "Test MacBook Pro, MacBook Air, iMac & Studio Display",
    description: "Apple displays feature Liquid Retina XDR Mini-LED, IPS Retina, or external 4K/5K panels. Test for backlight bleed, stuck subpixels, and uniform color calibration.",
    displayTech: "Liquid Retina XDR Mini-LED, IPS Retina, Studio Display 5K",
    prepTips: [
      "Disable True Tone and Night Shift in System Settings > Displays.",
      "Set color profile to standard 'Color LCD' or default factory profile.",
      "Press 'F' or click Enter Fullscreen to hide the macOS Dock and menu bar.",
      "Inspect display from normal viewing distance (approx. 50-70cm).",
    ],
    testSlug: "/mac-screen-test",
    deadSlug: "/mac-dead-pixel-test",
  },
  windows: {
    name: "Windows PC & Monitors",
    tagline: "Test Gaming Monitors, Laptops, OLED & 4K Displays",
    description: "Inspect Dell, ASUS, LG, Samsung, Lenovo, HP, MSI, Acer, and Alienware monitors for stuck subpixels, IPS glow, backlight bleeding, and refresh rate artifacts.",
    displayTech: "IPS, Fast IPS, VA, QD-OLED, WOLED, Mini-LED, TN",
    prepTips: [
      "Turn off Windows Night Light (Start > Settings > System > Display).",
      "Ensure HDR mode is configured properly or temporarily toggled if checking SDR gamut.",
      "Press 'F' or F11 to trigger browser fullscreen and hide taskbar.",
      "Check in a dimly lit environment to accurately inspect backlight bleed.",
    ],
    testSlug: "/windows-screen-test",
    deadSlug: "/windows-dead-pixel-test",
  },
  other: {
    name: "Smart TV & External Displays",
    tagline: "Test 4K/8K TVs, Projectors & Digital Signage",
    description: "Inspect LG OLED, Samsung QLED, Sony Bravia, TCL, Hisense, and projector displays for dead clusters, dirty screen effect, and local dimming anomalies.",
    displayTech: "OLED, QLED, QD-Mini LED, Direct Full Array LED, Laser DLP",
    prepTips: [
      "Open your smart TV's built-in web browser (e.g. LG webOS, Samsung Tizen, Android TV).",
      "Set Picture Mode to Standard or Movie mode.",
      "Maximize browser to fullscreen.",
      "Examine panel at center angle to minimize viewing angle color shift.",
    ],
    testSlug: "/display-test",
    deadSlug: "/dead-pixel-test",
  },
};

export const FAQ_ITEMS = [
  {
    question: "How do I test my screen for dead pixels?",
    answer: "Open PixelCheck365.com, click 'Start Screen Test' and enter fullscreen mode. The test displays solid pure colors (white, red, green, blue, black, and gray). Look carefully across your display: a dead pixel will appear as a permanent dark or black speck on bright backgrounds (like white and cyan).",
  },
  {
    question: "What is the difference between a dead pixel and a stuck pixel?",
    answer: "A dead pixel is permanently turned off—its transistor is non-functional, causing it to show up as a dark or black dot regardless of screen background. A stuck pixel is stuck in an 'on' state on one or more subpixels, appearing as a bright red, green, blue, or white glowing dot against a dark or black backdrop.",
  },
  {
    question: "Can a dead or stuck pixel be fixed?",
    answer: "True dead pixels (where the transistor is physically dead) cannot usually be fixed by software. However, stuck pixels can sometimes be revived using rapidly flashing color sequences (which stimulate the liquid crystals) or by gently massaging the area with a soft microfiber cloth on certain LCD panels. We recommend checking your manufacturer's warranty first.",
  },
  {
    question: "Can I test an iPhone or Android screen online?",
    answer: "Yes. PixelCheck365 is 100% mobile-optimized. Open the site in Safari or Chrome, tap 'Start Screen Test', and tap the full-screen button. You can swipe left and right to navigate colors or use Auto-Test mode to cycle automatically.",
  },
  {
    question: "Does PixelCheck365 upload my screen or collect personal data?",
    answer: "No. PixelCheck365 operates 100% client-side inside your browser. No images, camera feeds, device identifiers, or screen captures are recorded or sent to any server. Your privacy is fully preserved.",
  },
  {
    question: "Can browser tests detect physical resolution with 100% certainty?",
    answer: "Browsers report CSS viewport dimensions and device pixel ratio (DPR). Because operating systems apply display scaling (e.g., 125%, 150%, 200% Retina scaling), the reported viewport differs from the raw physical panel resolution. PixelCheck365 accurately labels this as browser viewport data.",
  },
  {
    question: "What should I look for during the Screen Uniformity Test?",
    answer: "Look for uneven brightness (clouding or shadows), backlight bleed around the edges/corners (common in LCD/IPS panels), dirty screen effect (DSE), or color temperature shifts (e.g., one side looking warmer or more pink than the other).",
  },
  {
    question: "How many dead pixels are covered under manufacturer warranty?",
    answer: "Most monitor and laptop manufacturers follow the ISO 9241-307 standard (Class II displays), which typically allows up to 2-5 defective pixels before qualifying for warranty replacement. However, high-end brands often offer 'Zero Bright Dot' guarantees for stuck bright pixels in the first 30-90 days.",
  },
];
